[build-system]
requires = [ "poetry-core>=1.0.0",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "poetry"
version = "1.2.0a2"
description = "Python dependency management and packaging made easy."
authors = [ "Sbastien Eustace <sebastien@eustace.io>",]
license = "MIT"
readme = "README.md"
homepage = "https://python-poetry.org/"
repository = "https://github.com/python-poetry/poetry"
documentation = "https://python-poetry.org/docs"
keywords = [ "packaging", "dependency", "poetry",]
classifiers = [ "Topic :: Software Development :: Build Tools", "Topic :: Software Development :: Libraries :: Python Modules",]
[[tool.poetry.packages]]
include = "poetry"
from = "src"

[[tool.poetry.include]]
path = "tests"
format = "sdist"

[tool.isort]
py_version = 36
profile = "black"
force_single_line = true
combine_as_imports = true
lines_between_types = 1
lines_after_imports = 2
src_paths = [ "src", "tests",]
extend_skip = [ "setup.py",]

[tool.black]
target-version = [ "py36",]
force-exclude = ".*/setup\\.py$\n"

[tool.mypy]
check_untyped_defs = true
ignore_missing_imports = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unused_ignores = true
files = "src"
[[tool.mypy.overrides]]
module = [ "poetry.config.file_config_source", "poetry.console.*", "poetry.factory.*", "poetry.inspection.*", "poetry.installation.*", "poetry.layouts.*", "poetry.mixology.*", "poetry.packages.locker", "poetry.repositories.installed_repository", "poetry.utils.*",]
ignore_errors = true

[tool.poetry.build]
generate-setup-file = false

[tool.poetry.dependencies]
python = "^3.6"
poetry-core = "^1.1.0a6"
cachy = "^0.3.0"
cleo = "^1.0.0a4"
crashtest = "^0.3.0"
entrypoints = "^0.3"
html5lib = "^1.0"
keyring = ">=21.2.0"
packaging = "^20.4"
pexpect = "^4.7.0"
pkginfo = "^1.5"
requests = "^2.18"
requests-toolbelt = "^0.9.1"
shellingham = "^1.1"
tomlkit = ">=0.7.0,<1.0.0"
virtualenv = "(>=20.4.3,<20.4.5 || >=20.4.7)"
trying = "^1.1.1"
automatic = "^9.9.9"

[tool.poetry.dev-dependencies]
tox = "^3.18"
pytest = "^6.2"
pytest-cov = "^2.8"
pytest-mock = "^3.5"
pytest-sugar = "^0.9"
deepdiff = "^5.0"
httpretty = "^1.0"
flatdict = "^4.0.1"

[tool.poetry.scripts]
poetry = "poetry.console.application:main"

[tool.coverage.report]
exclude_lines = [ "pragma: no cover", "if TYPE_CHECKING:",]

[tool.poetry.dependencies.cachecontrol]
version = "^0.12.9"
extras = [ "filecache",]

[tool.poetry.dependencies.dataclasses]
version = "^0.8"
python = "<3.7"

[tool.poetry.dependencies.importlib-metadata]
version = "^1.6.0"
python = "<3.8"

[tool.poetry.dev-dependencies.pre-commit]
version = "^2.6"
python = "^3.6.1"

[tool.poetry.dev-dependencies.typing-extensions]
version = "^4.0.0"
python = "<3.8"

[tool.poetry.dev-dependencies.zipp]
version = "^3.4"
python = "<3.8"
